In [228]:
import numpy as np
import pandas as pd

In [229]:
#from modules.data_collection import scrape
#scrape()

In [230]:
data1 = pd.read_csv("data/products1.csv")
data2 = pd.read_csv("data/products2.csv")

In [231]:
data1.head()

                   Name       Price           Category
0  Spaghetti 500g EXTRA   90,00 د.ج  Pâtes et Couscous
1  Spaghetti 500g EXTRA   90,00 د.ج  Pâtes et Couscous
2  FUSILLI 500g Garrido  115,00 د.ج  Pâtes et Couscous
3  FUSILLI 500g Garrido  115,00 د.ج  Pâtes et Couscous
4      NIDI 500G محبوبة  180,00 د.ج  Pâtes et Couscous

In [232]:
data1.duplicated().sum()

np.int64(189)

In [233]:
data1.isna().sum()

Name        0
Price       0
Category    0
dtype: int64

In [234]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      378 non-null    str
 1   Price     378 non-null    str
 2   Category  378 non-null    str
dtypes: str(3)
memory usage: 9.0 KB

In [235]:
data1.describe()

                        Name      Price           Category
count                    378        378                378
unique                   189         63                  8
top     Spaghetti 500g EXTRA  95,00 د.ج  Pâtes et Couscous
freq                       2         34                138

In [236]:
# drop the duplicates in data1
data1.drop_duplicates(inplace=True)

In [237]:
data1.describe()

                        Name      Price           Category
count                    189        189                189
unique                   189         63                  8
top     Spaghetti 500g EXTRA  95,00 د.ج  Pâtes et Couscous
freq                       1         17                 69

In [238]:
# clean the price field (to convert it from str to float)
data1["Price"] = (
    data1["Price"]
    .astype(str)
    .str.replace("د.ج", "", regex=False)
    .str.replace(",", ".", regex=False)
    .str.replace(" ", "", regex=False)
    .str.strip()
)

In [239]:
data1.head()

                       Name   Price           Category
0      Spaghetti 500g EXTRA   90.00  Pâtes et Couscous
2      FUSILLI 500g Garrido  115.00  Pâtes et Couscous
4          NIDI 500G محبوبة  180.00  Pâtes et Couscous
6   GNOCCHETTI  500G البركة  110.00  Pâtes et Couscous
8  CHAKHCHOUKHA 500G البركة  110.00  Pâtes et Couscous

In [240]:
data1.tail()

                                  Name   Price         Category
368       BISCUITS MAXON XL CACAO 400G  180.00  Epicerie-Sucree
370  BISCUITS MEGA DREAM CHOCOLAT 320G  110.00  Epicerie-Sucree
372    BISCUITS MEGA DREAM FRAISE 320G  110.00  Epicerie-Sucree
374       PATE A TARTINER OPTILLA 700G  470.00  Epicerie-Sucree
376          CHOCOLAT POUDRE NOVA 500G  325.00  Epicerie-Sucree

In [241]:
# convert the price to numeric values
data1["Price"] = pd.to_numeric(data1["Price"], errors="coerce")

In [242]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 189 entries, 0 to 376
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      189 non-null    str
 1   Price     182 non-null    float64
 2   Category  189 non-null    str
dtypes: float64(1), str(2)
memory usage: 4.6 KB

In [243]:
data2.head()

                Name              Price           Category
0                Ail             900 DA  Fruits et Légumes
1  Ail Rouge en Vrac     60 DA – 600 DA  Fruits et Légumes
2             Ananas  120 DA – 1,200 DA  Fruits et Légumes
3       Anchois Vrac  250 DA – 2,500 DA  Fruits et Légumes
4      Artichaut 1kg             250 DA  Fruits et Légumes

In [244]:
data2.tail()

                         Name   Price              Category
137     Semoule Fine Mama 5Kg  390 DA  Semoulerie et Farine
138   Semoule Grosse Mama 1KG  100 DA  Semoulerie et Farine
139   Semoule Grosse Mama 2kg  170 DA  Semoulerie et Farine
140  Semoule Moyenne Mama 1kg   90 DA  Semoulerie et Farine
141  Semoule Moyenne Mama 2kg  235 DA  Semoulerie et Farine

In [245]:
data2.describe()

                     Name     Price           Category
count                 142       142                142
unique                130        77                  3
top     Pomme Jaune Super  1,200 DA  Fruits et Légumes
freq                    2         9                 96

In [246]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      142 non-null    str
 1   Price     142 non-null    str
 2   Category  142 non-null    str
dtypes: str(3)
memory usage: 3.5 KB

In [247]:
# drop duplicates in data2
data2.drop_duplicates(inplace=True)

In [248]:
data2.describe()

       Name     Price           Category
count   130       130                130
unique  130        77                  3
top     Ail  1,200 DA  Fruits et Légumes
freq      1         9                 84

In [249]:
# clean the price field
data2["Price"] = (
    data2["Price"]
    .astype(str)
    .str.replace("DA", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(" ", "", regex=False)
    .str.strip()
)

In [250]:
data2.head()

                Name      Price           Category
0                Ail        900  Fruits et Légumes
1  Ail Rouge en Vrac    60 –600  Fruits et Légumes
2             Ananas  120 –1200  Fruits et Légumes
3       Anchois Vrac  250 –2500  Fruits et Légumes
4      Artichaut 1kg        250  Fruits et Légumes

In [251]:
def convert_value(val):
    if pd.isna(val):
        return np.nan
        
    val = val.replace("–", "-")
    
    if "-" in val:
        parts = val.split("-")
        try:
            nums = [float(p) for p in parts if p != ""]
            return sum(nums) / len(nums)
        except:
            return np.nan
    try:
        return float(val)
    except:
        return np.nan
"""
    convert the price to numeric values (float) and for those who are represented by intervals
    we compute them by the mean
"""
data2["Price"] = data2["Price"].apply(convert_value)

In [252]:
data2.head()

                Name   Price           Category
0                Ail   900.0  Fruits et Légumes
1  Ail Rouge en Vrac   330.0  Fruits et Légumes
2             Ananas   660.0  Fruits et Légumes
3       Anchois Vrac  1375.0  Fruits et Légumes
4      Artichaut 1kg   250.0  Fruits et Légumes

In [253]:
data2.info()

<class 'pandas.DataFrame'>
Index: 130 entries, 0 to 141
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      130 non-null    str
 1   Price     130 non-null    float64
 2   Category  130 non-null    str
dtypes: float64(1), str(2)
memory usage: 4.1 KB

In [254]:
# concatenate data1 and data2
data = pd.concat([data1, data2], axis=0)
data.describe()

             Price
count   312.000000
mean    273.958333
std     305.327590
min      25.000000
25%      95.000000
50%     165.000000
75%     296.250000
max    1925.000000

In [255]:
data.info()

<class 'pandas.DataFrame'>
Index: 319 entries, 0 to 141
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      319 non-null    str
 1   Price     312 non-null    float64
 2   Category  319 non-null    str
dtypes: float64(1), str(2)
memory usage: 10.0 KB

In [256]:
# drop the nan rows in the data (since they are only 7 rows)
data.dropna(inplace=True)

In [257]:
data.info()

<class 'pandas.DataFrame'>
Index: 312 entries, 0 to 141
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      312 non-null    str
 1   Price     312 non-null    float64
 2   Category  312 non-null    str
dtypes: float64(1), str(2)
memory usage: 9.8 KB

In [258]:
import re

In [259]:
# a function that extracts the quantity from the name with regex (regular expressions)
def extract_quantity(name, category):
    n = name.lower()
    # fruits & vegetables -> always per kg
    if category in ('Fruits et Légumes', 'Fruits Secs'):
        m = re.search(r'(\d+)\s*kg\b', n)
        if m:
            return f"{int(m.group(1)) * 1000} g"
        return "1000 g"
    # drinks -> convert to ml
    if category == 'Boisson':
        m = re.search(r'(\d+)\s*cl\b', n)
        if m:
            return f"{int(m.group(1)) * 10} ml"
        m = re.search(r'(\d+(?:[.,]\d+)?)\s*l\b', n)
        if m:
            return f"{int(float(m.group(1)) * 1000)} ml"
    # everything else -> look for g or kg in name
    m = re.search(r'(\d+)\s*g\b', n)
    if m:
        return f"{m.group(1)} g"
    m = re.search(r'(\d+)\s*kg\b', n)
    if m:
        return f"{int(m.group(1)) * 1000} g"
    return np.nan

data['Quantity'] = data.apply(
    lambda row: extract_quantity(row['Name'], row['Category']), axis=1
)

In [260]:
data.isna().sum()

Name         0
Price        0
Category     0
Quantity    27
dtype: int64

In [261]:
# then I have assigned qunatitites manually for products that does'nt contain quantities in their names (23 product)
data = pd.read_csv("data/products_manually_modified.csv")

In [262]:
data.isna().sum()

Name        0
Price       0
Category    0
Quantity    4
dtype: int64

In [263]:
# drop the 4 products that I didn't find their quantities
data.dropna(inplace=True)

In [264]:
# add nutritional unit field
data['Nutritional Unit'] = data['Quantity'].apply(
    lambda q: 'per 100 ml' if 'ml' in str(q) else 'per 100 g'
)

In [265]:
# from nutrition_db we map each product to it's nutritional unit
# produce_name_map is a dictionary that maps fruits and vegetables to their values
# here the order of mapping matters 
from data.nutrition_data import NUTRITION_DB, PRODUCE_NAME_MAP
def map_product_to_key(row):
    name = str(row['Name']).lower()
    cat  = str(row['Category'])

    if "confiture" in name:       return 'jam'
    if any(x in name for x in ["gazeuse", "slim", "selecto", "coca"]): return 'soda'
    if any(x in name for x in ["biscuits", "galette", "céréales"]):       return 'biscuits'
    for key in sorted(PRODUCE_NAME_MAP, key=len, reverse=True):
        if key in name:
            return PRODUCE_NAME_MAP[key]
    if "couscous" in name:        return 'couscous'
    if cat == 'Pâtes et Couscous': return 'dry_pasta'
    if any(x in name for x in ["candy choco", "chocolat"]): return 'chocolate_milk'
    if "lait" in name:
        return 'skim_milk' if any(x in name for x in ["ecreme", "silhouette"]) else 'whole_milk'
    if "margarine" in name:       return 'margarine'
    if "fromage"   in name:       return 'processed_cheese'
    if "riz"       in name:       return 'rice'
    if "lentille"  in name:       return 'lentils'
    if "pois chiche" in name:     return 'chickpeas'
    if "farine"    in name:       return 'flour'
    if "semoule"   in name:       return 'semolina'
    if "sucre"     in name:       return 'sugar'
    if "thon" in name:
        if "tomate"  in name:     return 'tuna_tomato'
        return 'tuna_natural' if "naturel" in name else 'tuna_in_oil'
    if "huile" in name or cat == 'Huiles et Vinaigre':
        if "vinaigre"   in name:  return 'vinegar'
        if "mayonnaise" in name:  return 'mayonnaise'
        return 'oil'
    if any(x in name for x in ["gaufrette", "gullon"]): return 'biscuits'
    if "pois cassés" in name:     return 'split_peas'
    if any(x in name for x in ["cafe", "café"]):  return 'coffee'
    if any(x in name for x in ["haraissa", "hrouss", "hrissa", "harissa"]): return 'harissa'
    if "haricot" in name and cat == "Légumes Secs": return 'kidney_beans'
    if "tartiner" in name:        return 'spread'

    TOMATO_FRESH_RE = re.compile(r'^(tomate)$')
    if "tomate" in name:
        if TOMATO_FRESH_RE.match(name):
            return 'tomato'
        else:
            return 'tomato_paste'
    return 'other'

data['Nutri_Key'] = data.apply(map_product_to_key, axis=1)

nutri_cols = ['Calories (g)', 'Protein (g)', 'Total_Fat (g)', 'Saturated_Fat (g)', 'Carbohydrates (g)', 'Sugar (g)', 'Fiber (g)', 'Sodium (mg)']

for i, col in enumerate(nutri_cols):
    data[col] = data['Nutri_Key'].map(lambda x: NUTRITION_DB.get(x, NUTRITION_DB['other'])[i])
# for the products that I didn't find their nutritional values i imputed them with the mean of their categry porducts nutritional values
data[nutri_cols] = data.groupby('Category')[nutri_cols].transform(lambda x: x.fillna(x.mean()))
# drop the nutri_key field
data.drop(columns=['Nutri_Key'], inplace=True)

In [266]:
data.isna().sum()

Name                 0
Price                0
Category             0
Quantity             0
Nutritional Unit     0
Calories (g)         0
Protein (g)          0
Total_Fat (g)        0
Saturated_Fat (g)    0
Carbohydrates (g)    0
Sugar (g)            0
Fiber (g)            0
Sodium (mg)          0
dtype: int64

In [267]:
# export the products data
data.insert(0, "PID", np.arange(1, len(data) + 1))
data.to_csv("data/products.csv", index=False, encoding="utf-8-sig")

In [268]:
recipes_header = [
    "RID",
    "Name",
    "type", # (Breakfast, lunch, dinner)
    "Category", # (Vegitarian, chicken etc...)
    "total_price", # calculated 
    "provided_calories" # calculated
]
recipes_data = pd.DataFrame(columns = recipes_header)

recipe_ingredient_header = [
    "PID", # from products data
    "RID", # from recipes data
    "Quantity"
]
recipe_ingredient_data = pd.DataFrame(columns = recipe_ingredient_header)

recipes_data.to_csv("data/recipes.csv", index=False, encoding="utf-8-sig")
recipe_ingredient_data.to_csv("data/recipe_ingredient.csv", index=False, encoding="utf-8-sig")

## Recipe Consolidation Workflow - PID-Based System

### Instructions :

1. **Get the template**: Copy `data/recipe_template.csv` into data/recipes_input and rename it to 'your-name.csv'
2. **Look up PIDs**: Find product PIDs in `data/products.csv` for each ingredient you want to use
3. **Fill in your recipes**: Replace PIDs and quantities with your own recipes

you can run the consolidation cell bellow this to test if your recipes are being integrated correctly.

###  CSV Format:

```
Name,Type,Category,PIDs,Quantities
Breakfast Omelette,Breakfast,Vegetarian,"3;191;200;162;152","3;100 g;50 g;15 ml;1 g"
```

- **Name**: Recipe name
- **Type**: Breakfast, Lunch, or Dinner
- **Category**: Vegetarian, Non-Vegetarian, Vegan, etc.
- **PIDs**: Semicolon-separated product IDs (from data/products.csv)
- **Quantities**: Semicolon-separated quantities with units (e.g., "100 g", "15 ml", "3")

In [269]:
from modules.recipe_consolidation import run_consolidation

# Run the consolidation process
recipes_df, recipe_ingredients_df = run_consolidation(
    products_csv="data/products.csv",
    recipes_input_dir="data/recipes_input"
)

============================================================
RECIPE CONSOLIDATION PROCESS
============================================================

1. Loading individual recipe files...
Found 5 recipe file(s)
   Loaded 214 recipes

2. Calculating totals for each recipe...

3. Generating output CSVs...

4. Validation Report:
   ✓ Recipes consolidated: 214
   ⚠ Warnings: 0
   ✗ Errors: 0

5. Export Complete:
   ✓ data/recipes.csv (214 recipes)
   ✓ data/recipe_ingredient.csv (960 items)

In [270]:
# View consolidated recipes
print("CONSOLIDATED RECIPES")
print(recipes_df.head(10))
print("\nRECIPE INGREDIENTS MAPPING")
print(recipe_ingredients_df.head(15))

CONSOLIDATED RECIPES
   RID                   Name       type        Category  total_price  \
0    1                M'semen  Breakfast      Vegetarian        58.02
1    2                  Rfiss  Breakfast      Vegetarian        58.37
2    3                Tchicha      Lunch  Non-Vegetarian       223.27
3    4           Chorba Hamra      Lunch  Non-Vegetarian       276.23
4    5         Chorba el Djaj      Lunch  Non-Vegetarian       329.67
5    6                 Hlalem      Lunch  Non-Vegetarian       265.77
6    7                Doubara      Lunch      Vegetarian       107.52
7    8                 Osbane     Dinner  Non-Vegetarian       351.67
8    9               M'hammer     Dinner  Non-Vegetarian      1203.86
9   10  Chakhchoukha Sahraoui     Dinner  Non-Vegetarian       309.83

   provided_calories  provided_protein  provided_fat  provided_carbs
0             822.14             20.00         21.95          136.56
1            1328.00             44.80          2.80          271.60
2             927.24             45.12         24.76          130.69
3             710.64             48.32         30.76           65.89
4             780.04             52.32         30.66           76.75
5             838.24             46.02         29.76          105.09
6             939.24             42.92         27.46          136.99
7            1128.64             63.82         34.66          144.29
8            1545.80            162.55         86.60           42.03
9             883.24             52.02         31.86          105.99

RECIPE INGREDIENTS MAPPING
    PID  RID Quantity
0   200    1    150 g
1     9    1     50 g
2   162    1    20 ml
3   152    1      2 g
4    17    1   100 ml
5     9    2    200 g
6   301    2    100 g
7   308    2     10 g
8   306    2     30 g
9   302    2    20 ml
10    9    3    150 g
11  110    3    120 g
12  191    3     80 g
13  204    3    100 g
14  162    3    15 ml

In [271]:
recipes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RID                214 non-null    int64
 1   Name               214 non-null    str
 2   type               214 non-null    str
 3   Category           214 non-null    str
 4   total_price        214 non-null    float64
 5   provided_calories  214 non-null    float64
 6   provided_protein   214 non-null    float64
 7   provided_fat       214 non-null    float64
 8   provided_carbs     214 non-null    float64
dtypes: float64(5), int64(1), str(3)
memory usage: 15.2 KB

In [272]:
recipes_df.describe()

,RID,total_price,provided_calories,provided_protein,provided_fat,provided_carbs
count,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000
mean,107.500000,236.235935,658.297477,41.550374,21.862804,74.359953
std,61.920648,182.450650,364.317297,22.181586,14.486019,74.344312
min,1.000000,22.320000,127.040000,1.280000,0.500000,1.350000
25%,54.250000,90.667500,362.382500,28.890000,12.732500,8.910000
50%,107.500000,166.715000,561.730000,40.245000,18.550000,53.925000
75%,160.750000,364.445000,905.410000,53.650000,29.732500,130.862500
max,214.000000,1203.860000,1707.440000,162.550000,150.300000,328.840000